export const productos = [
  {
    id: 1,
    title: "Scottex",
    descripcion: "Aprovecha la promo 2 x 1",
    price: 600,
    pictureUrl: "cocina.jpg",
  },
  {
    id: 2,
    title: "Extra Familiar",
    descripcion: "el mas suave de todos",
    price: 5,
    pictureUrl: "rollo.jpg",
  },
  {
    id: 3,
    title: "Cuadrada",
    descripcion: "Ideal para fiestas",
    price: 7.5,
    pictureUrl: "bandeja1.jpg",
  },
  {
    id: 4,
    title: "Sussex",
    descripcion: "Lleva la mejor calidad",
    price: 850,
    pictureUrl: "cocina2.jpg",
  },
  {
    id: 5,
    title: "Doble Rollo",
    descripcion: "el mas suave de todos",
    price: 5,
    pictureUrl: "rollo2.jpg",
  },
  {
    id: 6,
    title: "Rectangular",
    descripcion: "Bandeja de carton multiusos",
    price: 7.5,
    pictureUrl: "bandeja2.jpg",
  },
  {
    id: 7,
    title: "Felpita",
    descripcion: "Para mas duracion",
    price: 15,
    pictureUrl: "cocina3.jpg",
  },
  {
    id: 8,
    title: "Nacional",
    descripcion: "el mas suave de todos",
    price: 5,
    pictureUrl: "rollo3.jpg",
  },
  {
    id: 9,
    title: "Circular",
    descripcion: "La mejor resistencia",
    price: 7.5,
    pictureUrl: "bandeja3.jpg",
  },
];
